# .github/workflows/convert-js-to-txt.yml
name: Convert JS to TXT

on:
  pull_request:
    paths:
      - 'example/*' # Only run when files in the example directory are changed

jobs:
  convert-js-to-txt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Check if example directory changed
      id: check-example-changed
      run: |
        if git rev-parse HEAD~ >/dev/null 2>&1; then
          git diff --quiet HEAD HEAD~ -- example
          if [ $? -eq 0 ]; then
            echo "example_changed=false" >> $GITHUB_OUTPUT
          else
            echo "example_changed=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "example_changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Convert JS to TXT
      if: steps.check-example-changed.outputs.example_changed == 'true'
      run: node parser.js
      working-directory: ./example

    - name: Commit and push changes
      if: steps.check-example-changed.outputs.example_changed == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add example/generated
        git commit -m "Generate text files from JavaScript files"
        git push origin HEAD:${{ github.head_ref }}
