# .github/workflows/convert-js-to-txt.yml
name: Convert JS to TXT

on:
  pull_request:
    paths:
      - 'example/*' # Only run when files in the example directory are changed

jobs:
  convert-js-to-txt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Check if index.js changed
      id: files_changed_check_
      run: |
        git diff --quiet example/index.js || echo "index_changed=true" >> $GITHUB_OUTPUT
        git diff --quiet example/generated || echo "generated_changed=true" >> $GITHUB_OUTPUT
        git diff --quiet example/ || echo "example_changed=true" >> $GITHUB_OUTPUT

    - shell: pwsh
      name: Check if files changed
      id: files_changed_check
      run: |
        git diff --quiet example/index.js HEAD^ HEAD || echo "index_changed=true" >> $GITHUB_OUTPUT
        git diff -- quiet example/generated HEAD^ HEAD || echo "generated_changed=true" >> $GITHUB_OUTPUT
        $exampleDiff = git diff --name-only HEAD^ HEAD
        

    - name: Convert JS to TXT
      if: steps.check_file_changed.outputs.run_job == 'true'
      run: node parser.js
      working-directory: .

    - name: Setup and add files
      id: setup_add_filed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add example/generated index.js
        if [ -z "$(git status --porcelain)"]; then
          echo "No changes to commit, omitting comit"
          echo "can_commit=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected, proceeding to commit and push"
          echo "can_commit=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.setup_add_files.outputs.can_commit == 'true'
      run: |
        git commit -m "Generate text files from JavaScript files"
        git push origin HEAD:${{ github.head_ref }}
