# .github/workflows/convert-js-to-txt.yml
name: Convert JS to TXT

on:
  pull_request:
    paths:
      - 'example/*' # Only run when files in the example directory are changed

jobs:
  convert-js-to-txt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache generated files
      id: cache-generated
      uses: actions/cache@v3
      with:
        path: example/generated
        key: ${{ runner.os }}-generated-${{ hashFiles('example/**/*') }}
        restore-keys: |
          ${{ runner.os }}-generated-

    - name: Convert JS to TXT
      if: steps.cache-generated.outputs.cache-hit != 'true'
      run: node parser.js
      working-directory: ./example

    - name: Commit and push changes
      if: steps.cache-generated.outputs.cache-hit != 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add example/generated
        git commit -m "Generate text files from JavaScript files"
        git push origin HEAD:${{ github.head_ref }}
